name: devSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    container:
      image: node:14-bullseye

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn
      - name: Generate Prisma client
        run: yarn redwood prisma generate
      - name: Run tests
        run: yarn redwood test

  sast:
    name: SAST - Dependency Scan
    runs-on: ubuntu-latest
    container:
      image: node:18-bullseye

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn --ignore-engines
      - name: Install retire.js
        run: npm install -g retire
      - name: Run retire.js
        run: cd web; retire --path web

  build:
    name: Build Application
    needs: unit-tests
    runs-on: ubuntu-latest
    container:
      image: node:14-bullseye

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn
      - name: Build application
        run: yarn redwood build

  deploy-qa:
    name: Deploy to QA
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Deploy to QA environment
        run: echo "Deployed to QA environment with AWS S3 bucket magic or Azure container magic"

  dast:
    name: DAST - Nuclei Scan
    needs: deploy-qa
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Install nuclei
        run: go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
      - name: Run nuclei scan
        run: nuclei -u https://flippedcoding.com

