name: devSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    container:
      image: node:14-bullseye

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn
      - name: Generate Prisma client
        run: yarn redwood prisma generate
      - name: Run tests
        run: yarn redwood test

  build:
    name: Build Application
    needs: unit-tests
    runs-on: ubuntu-latest
    container:
      image: node:14-bullseye

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn
      - name: Build application
        run: yarn redwood build

